// 全国省市选项（省 → 城市 两级），供投递的城市级联选择使用（筛选与表单共用同一份）。
//
// 数据来源：element-china-area-data@6.1.0 的 regionData，**构建期提取一次**后内嵌，
// 运行时不含该依赖。三条口径：
//   1. value 去掉尾部「市」字——库内既有数据存的是「南京」而非「南京市」，
//      不去后缀会让选择结果与历史数据分裂成两个筛选条件；
//   2. 第二级 = 地级市 + 该省下辖的县级市（昆山、常熟等，「投递到县级市」也能筛到）；
//   3. 直辖市不设第二级（其下辖是「区」，市一级就是它自己），选中即一级。

export const CITY_OPTIONS = [
  { value: '北京', label: '北京市' },
  { value: '天津', label: '天津市' },
  {
    value: '河北省',
    label: '河北省',
    children: [
    { value: '石家庄', label: '石家庄市' },
    { value: '辛集', label: '辛集市' },
    { value: '晋州', label: '晋州市' },
    { value: '新乐', label: '新乐市' },
    { value: '唐山', label: '唐山市' },
    { value: '遵化', label: '遵化市' },
    { value: '迁安', label: '迁安市' },
    { value: '滦州', label: '滦州市' },
    { value: '秦皇岛', label: '秦皇岛市' },
    { value: '邯郸', label: '邯郸市' },
    { value: '武安', label: '武安市' },
    { value: '邢台', label: '邢台市' },
    { value: '南宫', label: '南宫市' },
    { value: '沙河', label: '沙河市' },
    { value: '保定', label: '保定市' },
    { value: '涿州', label: '涿州市' },
    { value: '定州', label: '定州市' },
    { value: '安国', label: '安国市' },
    { value: '高碑店', label: '高碑店市' },
    { value: '张家口', label: '张家口市' },
    { value: '承德', label: '承德市' },
    { value: '平泉', label: '平泉市' },
    { value: '沧州', label: '沧州市' },
    { value: '泊头', label: '泊头市' },
    { value: '任丘', label: '任丘市' },
    { value: '黄骅', label: '黄骅市' },
    { value: '河间', label: '河间市' },
    { value: '廊坊', label: '廊坊市' },
    { value: '霸州', label: '霸州市' },
    { value: '三河', label: '三河市' },
    { value: '衡水', label: '衡水市' },
    { value: '深州', label: '深州市' }
    ]
  },
  {
    value: '山西省',
    label: '山西省',
    children: [
    { value: '太原', label: '太原市' },
    { value: '古交', label: '古交市' },
    { value: '大同', label: '大同市' },
    { value: '阳泉', label: '阳泉市' },
    { value: '长治', label: '长治市' },
    { value: '晋城', label: '晋城市' },
    { value: '高平', label: '高平市' },
    { value: '朔州', label: '朔州市' },
    { value: '怀仁', label: '怀仁市' },
    { value: '晋中', label: '晋中市' },
    { value: '介休', label: '介休市' },
    { value: '运城', label: '运城市' },
    { value: '永济', label: '永济市' },
    { value: '河津', label: '河津市' },
    { value: '忻州', label: '忻州市' },
    { value: '原平', label: '原平市' },
    { value: '临汾', label: '临汾市' },
    { value: '侯马', label: '侯马市' },
    { value: '霍州', label: '霍州市' },
    { value: '吕梁', label: '吕梁市' },
    { value: '孝义', label: '孝义市' },
    { value: '汾阳', label: '汾阳市' }
    ]
  },
  {
    value: '内蒙古自治区',
    label: '内蒙古自治区',
    children: [
    { value: '呼和浩特', label: '呼和浩特市' },
    { value: '包头', label: '包头市' },
    { value: '乌海', label: '乌海市' },
    { value: '赤峰', label: '赤峰市' },
    { value: '通辽', label: '通辽市' },
    { value: '霍林郭勒', label: '霍林郭勒市' },
    { value: '鄂尔多斯', label: '鄂尔多斯市' },
    { value: '呼伦贝尔', label: '呼伦贝尔市' },
    { value: '满洲里', label: '满洲里市' },
    { value: '牙克石', label: '牙克石市' },
    { value: '扎兰屯', label: '扎兰屯市' },
    { value: '额尔古纳', label: '额尔古纳市' },
    { value: '根河', label: '根河市' },
    { value: '巴彦淖尔', label: '巴彦淖尔市' },
    { value: '乌兰察布', label: '乌兰察布市' },
    { value: '丰镇', label: '丰镇市' },
    { value: '兴安盟', label: '兴安盟' },
    { value: '乌兰浩特', label: '乌兰浩特市' },
    { value: '阿尔山', label: '阿尔山市' },
    { value: '锡林郭勒盟', label: '锡林郭勒盟' },
    { value: '二连浩特', label: '二连浩特市' },
    { value: '锡林浩特', label: '锡林浩特市' },
    { value: '阿拉善盟', label: '阿拉善盟' }
    ]
  },
  {
    value: '辽宁省',
    label: '辽宁省',
    children: [
    { value: '沈阳', label: '沈阳市' },
    { value: '新民', label: '新民市' },
    { value: '大连', label: '大连市' },
    { value: '瓦房店', label: '瓦房店市' },
    { value: '庄河', label: '庄河市' },
    { value: '鞍山', label: '鞍山市' },
    { value: '海城', label: '海城市' },
    { value: '抚顺', label: '抚顺市' },
    { value: '本溪', label: '本溪市' },
    { value: '丹东', label: '丹东市' },
    { value: '东港', label: '东港市' },
    { value: '凤城', label: '凤城市' },
    { value: '锦州', label: '锦州市' },
    { value: '凌海', label: '凌海市' },
    { value: '北镇', label: '北镇市' },
    { value: '营口', label: '营口市' },
    { value: '盖州', label: '盖州市' },
    { value: '大石桥', label: '大石桥市' },
    { value: '阜新', label: '阜新市' },
    { value: '辽阳', label: '辽阳市' },
    { value: '灯塔', label: '灯塔市' },
    { value: '盘锦', label: '盘锦市' },
    { value: '铁岭', label: '铁岭市' },
    { value: '调兵山', label: '调兵山市' },
    { value: '开原', label: '开原市' },
    { value: '朝阳', label: '朝阳市' },
    { value: '北票', label: '北票市' },
    { value: '凌源', label: '凌源市' },
    { value: '葫芦岛', label: '葫芦岛市' },
    { value: '兴城', label: '兴城市' }
    ]
  },
  {
    value: '吉林省',
    label: '吉林省',
    children: [
    { value: '长春', label: '长春市' },
    { value: '榆树', label: '榆树市' },
    { value: '德惠', label: '德惠市' },
    { value: '公主岭', label: '公主岭市' },
    { value: '吉林', label: '吉林市' },
    { value: '蛟河', label: '蛟河市' },
    { value: '桦甸', label: '桦甸市' },
    { value: '舒兰', label: '舒兰市' },
    { value: '磐石', label: '磐石市' },
    { value: '四平', label: '四平市' },
    { value: '双辽', label: '双辽市' },
    { value: '辽源', label: '辽源市' },
    { value: '通化', label: '通化市' },
    { value: '梅河口', label: '梅河口市' },
    { value: '集安', label: '集安市' },
    { value: '白山', label: '白山市' },
    { value: '临江', label: '临江市' },
    { value: '松原', label: '松原市' },
    { value: '扶余', label: '扶余市' },
    { value: '白城', label: '白城市' },
    { value: '洮南', label: '洮南市' },
    { value: '大安', label: '大安市' },
    { value: '延边朝鲜族自治州', label: '延边朝鲜族自治州' },
    { value: '延吉', label: '延吉市' },
    { value: '图们', label: '图们市' },
    { value: '敦化', label: '敦化市' },
    { value: '珲春', label: '珲春市' },
    { value: '龙井', label: '龙井市' },
    { value: '和龙', label: '和龙市' }
    ]
  },
  {
    value: '黑龙江省',
    label: '黑龙江省',
    children: [
    { value: '哈尔滨', label: '哈尔滨市' },
    { value: '尚志', label: '尚志市' },
    { value: '五常', label: '五常市' },
    { value: '齐齐哈尔', label: '齐齐哈尔市' },
    { value: '讷河', label: '讷河市' },
    { value: '鸡西', label: '鸡西市' },
    { value: '虎林', label: '虎林市' },
    { value: '密山', label: '密山市' },
    { value: '鹤岗', label: '鹤岗市' },
    { value: '双鸭山', label: '双鸭山市' },
    { value: '大庆', label: '大庆市' },
    { value: '伊春', label: '伊春市' },
    { value: '铁力', label: '铁力市' },
    { value: '佳木斯', label: '佳木斯市' },
    { value: '同江', label: '同江市' },
    { value: '富锦', label: '富锦市' },
    { value: '抚远', label: '抚远市' },
    { value: '七台河', label: '七台河市' },
    { value: '牡丹江', label: '牡丹江市' },
    { value: '绥芬河', label: '绥芬河市' },
    { value: '海林', label: '海林市' },
    { value: '宁安', label: '宁安市' },
    { value: '穆棱', label: '穆棱市' },
    { value: '东宁', label: '东宁市' },
    { value: '黑河', label: '黑河市' },
    { value: '北安', label: '北安市' },
    { value: '五大连池', label: '五大连池市' },
    { value: '嫩江', label: '嫩江市' },
    { value: '绥化', label: '绥化市' },
    { value: '安达', label: '安达市' },
    { value: '肇东', label: '肇东市' },
    { value: '海伦', label: '海伦市' },
    { value: '大兴安岭地区', label: '大兴安岭地区' },
    { value: '漠河', label: '漠河市' }
    ]
  },
  { value: '上海', label: '上海市' },
  {
    value: '江苏省',
    label: '江苏省',
    children: [
    { value: '南京', label: '南京市' },
    { value: '无锡', label: '无锡市' },
    { value: '江阴', label: '江阴市' },
    { value: '宜兴', label: '宜兴市' },
    { value: '徐州', label: '徐州市' },
    { value: '新沂', label: '新沂市' },
    { value: '邳州', label: '邳州市' },
    { value: '常州', label: '常州市' },
    { value: '溧阳', label: '溧阳市' },
    { value: '苏州', label: '苏州市' },
    { value: '常熟', label: '常熟市' },
    { value: '张家港', label: '张家港市' },
    { value: '昆山', label: '昆山市' },
    { value: '太仓', label: '太仓市' },
    { value: '南通', label: '南通市' },
    { value: '启东', label: '启东市' },
    { value: '如皋', label: '如皋市' },
    { value: '海安', label: '海安市' },
    { value: '连云港', label: '连云港市' },
    { value: '淮安', label: '淮安市' },
    { value: '盐城', label: '盐城市' },
    { value: '东台', label: '东台市' },
    { value: '扬州', label: '扬州市' },
    { value: '仪征', label: '仪征市' },
    { value: '高邮', label: '高邮市' },
    { value: '镇江', label: '镇江市' },
    { value: '丹阳', label: '丹阳市' },
    { value: '扬中', label: '扬中市' },
    { value: '句容', label: '句容市' },
    { value: '泰州', label: '泰州市' },
    { value: '兴化', label: '兴化市' },
    { value: '靖江', label: '靖江市' },
    { value: '泰兴', label: '泰兴市' },
    { value: '宿迁', label: '宿迁市' }
    ]
  },
  {
    value: '浙江省',
    label: '浙江省',
    children: [
    { value: '杭州', label: '杭州市' },
    { value: '建德', label: '建德市' },
    { value: '宁波', label: '宁波市' },
    { value: '余姚', label: '余姚市' },
    { value: '慈溪', label: '慈溪市' },
    { value: '温州', label: '温州市' },
    { value: '瑞安', label: '瑞安市' },
    { value: '乐清', label: '乐清市' },
    { value: '龙港', label: '龙港市' },
    { value: '嘉兴', label: '嘉兴市' },
    { value: '海宁', label: '海宁市' },
    { value: '平湖', label: '平湖市' },
    { value: '桐乡', label: '桐乡市' },
    { value: '湖州', label: '湖州市' },
    { value: '绍兴', label: '绍兴市' },
    { value: '诸暨', label: '诸暨市' },
    { value: '嵊州', label: '嵊州市' },
    { value: '金华', label: '金华市' },
    { value: '兰溪', label: '兰溪市' },
    { value: '义乌', label: '义乌市' },
    { value: '东阳', label: '东阳市' },
    { value: '永康', label: '永康市' },
    { value: '衢州', label: '衢州市' },
    { value: '江山', label: '江山市' },
    { value: '舟山', label: '舟山市' },
    { value: '台州', label: '台州市' },
    { value: '温岭', label: '温岭市' },
    { value: '临海', label: '临海市' },
    { value: '玉环', label: '玉环市' },
    { value: '丽水', label: '丽水市' },
    { value: '龙泉', label: '龙泉市' }
    ]
  },
  {
    value: '安徽省',
    label: '安徽省',
    children: [
    { value: '合肥', label: '合肥市' },
    { value: '巢湖', label: '巢湖市' },
    { value: '芜湖', label: '芜湖市' },
    { value: '无为', label: '无为市' },
    { value: '蚌埠', label: '蚌埠市' },
    { value: '淮南', label: '淮南市' },
    { value: '马鞍山', label: '马鞍山市' },
    { value: '淮北', label: '淮北市' },
    { value: '铜陵', label: '铜陵市' },
    { value: '安庆', label: '安庆市' },
    { value: '桐城', label: '桐城市' },
    { value: '潜山', label: '潜山市' },
    { value: '黄山', label: '黄山市' },
    { value: '滁州', label: '滁州市' },
    { value: '天长', label: '天长市' },
    { value: '明光', label: '明光市' },
    { value: '阜阳', label: '阜阳市' },
    { value: '界首', label: '界首市' },
    { value: '宿州', label: '宿州市' },
    { value: '六安', label: '六安市' },
    { value: '亳州', label: '亳州市' },
    { value: '池州', label: '池州市' },
    { value: '宣城', label: '宣城市' },
    { value: '宁国', label: '宁国市' },
    { value: '广德', label: '广德市' }
    ]
  },
  {
    value: '福建省',
    label: '福建省',
    children: [
    { value: '福州', label: '福州市' },
    { value: '福清', label: '福清市' },
    { value: '厦门', label: '厦门市' },
    { value: '莆田', label: '莆田市' },
    { value: '三明', label: '三明市' },
    { value: '永安', label: '永安市' },
    { value: '泉州', label: '泉州市' },
    { value: '石狮', label: '石狮市' },
    { value: '晋江', label: '晋江市' },
    { value: '南安', label: '南安市' },
    { value: '漳州', label: '漳州市' },
    { value: '南平', label: '南平市' },
    { value: '邵武', label: '邵武市' },
    { value: '武夷山', label: '武夷山市' },
    { value: '建瓯', label: '建瓯市' },
    { value: '龙岩', label: '龙岩市' },
    { value: '漳平', label: '漳平市' },
    { value: '宁德', label: '宁德市' },
    { value: '福安', label: '福安市' },
    { value: '福鼎', label: '福鼎市' }
    ]
  },
  {
    value: '江西省',
    label: '江西省',
    children: [
    { value: '南昌', label: '南昌市' },
    { value: '景德镇', label: '景德镇市' },
    { value: '乐平', label: '乐平市' },
    { value: '萍乡', label: '萍乡市' },
    { value: '九江', label: '九江市' },
    { value: '瑞昌', label: '瑞昌市' },
    { value: '共青城', label: '共青城市' },
    { value: '庐山', label: '庐山市' },
    { value: '新余', label: '新余市' },
    { value: '鹰潭', label: '鹰潭市' },
    { value: '贵溪', label: '贵溪市' },
    { value: '赣州', label: '赣州市' },
    { value: '瑞金', label: '瑞金市' },
    { value: '龙南', label: '龙南市' },
    { value: '吉安', label: '吉安市' },
    { value: '井冈山', label: '井冈山市' },
    { value: '宜春', label: '宜春市' },
    { value: '丰城', label: '丰城市' },
    { value: '樟树', label: '樟树市' },
    { value: '高安', label: '高安市' },
    { value: '抚州', label: '抚州市' },
    { value: '上饶', label: '上饶市' },
    { value: '德兴', label: '德兴市' }
    ]
  },
  {
    value: '山东省',
    label: '山东省',
    children: [
    { value: '济南', label: '济南市' },
    { value: '青岛', label: '青岛市' },
    { value: '胶州', label: '胶州市' },
    { value: '平度', label: '平度市' },
    { value: '莱西', label: '莱西市' },
    { value: '淄博', label: '淄博市' },
    { value: '枣庄', label: '枣庄市' },
    { value: '滕州', label: '滕州市' },
    { value: '东营', label: '东营市' },
    { value: '烟台', label: '烟台市' },
    { value: '龙口', label: '龙口市' },
    { value: '莱阳', label: '莱阳市' },
    { value: '莱州', label: '莱州市' },
    { value: '招远', label: '招远市' },
    { value: '栖霞', label: '栖霞市' },
    { value: '海阳', label: '海阳市' },
    { value: '潍坊', label: '潍坊市' },
    { value: '青州', label: '青州市' },
    { value: '诸城', label: '诸城市' },
    { value: '寿光', label: '寿光市' },
    { value: '安丘', label: '安丘市' },
    { value: '高密', label: '高密市' },
    { value: '昌邑', label: '昌邑市' },
    { value: '济宁', label: '济宁市' },
    { value: '曲阜', label: '曲阜市' },
    { value: '邹城', label: '邹城市' },
    { value: '泰安', label: '泰安市' },
    { value: '新泰', label: '新泰市' },
    { value: '肥城', label: '肥城市' },
    { value: '威海', label: '威海市' },
    { value: '荣成', label: '荣成市' },
    { value: '乳山', label: '乳山市' },
    { value: '日照', label: '日照市' },
    { value: '临沂', label: '临沂市' },
    { value: '德州', label: '德州市' },
    { value: '乐陵', label: '乐陵市' },
    { value: '禹城', label: '禹城市' },
    { value: '聊城', label: '聊城市' },
    { value: '临清', label: '临清市' },
    { value: '滨州', label: '滨州市' },
    { value: '邹平', label: '邹平市' },
    { value: '菏泽', label: '菏泽市' }
    ]
  },
  {
    value: '河南省',
    label: '河南省',
    children: [
    { value: '郑州', label: '郑州市' },
    { value: '巩义', label: '巩义市' },
    { value: '荥阳', label: '荥阳市' },
    { value: '新密', label: '新密市' },
    { value: '新郑', label: '新郑市' },
    { value: '登封', label: '登封市' },
    { value: '开封', label: '开封市' },
    { value: '洛阳', label: '洛阳市' },
    { value: '平顶山', label: '平顶山市' },
    { value: '舞钢', label: '舞钢市' },
    { value: '汝州', label: '汝州市' },
    { value: '安阳', label: '安阳市' },
    { value: '林州', label: '林州市' },
    { value: '鹤壁', label: '鹤壁市' },
    { value: '新乡', label: '新乡市' },
    { value: '卫辉', label: '卫辉市' },
    { value: '辉县', label: '辉县市' },
    { value: '长垣', label: '长垣市' },
    { value: '焦作', label: '焦作市' },
    { value: '沁阳', label: '沁阳市' },
    { value: '孟州', label: '孟州市' },
    { value: '濮阳', label: '濮阳市' },
    { value: '许昌', label: '许昌市' },
    { value: '禹州', label: '禹州市' },
    { value: '长葛', label: '长葛市' },
    { value: '漯河', label: '漯河市' },
    { value: '三门峡', label: '三门峡市' },
    { value: '义马', label: '义马市' },
    { value: '灵宝', label: '灵宝市' },
    { value: '南阳', label: '南阳市' },
    { value: '邓州', label: '邓州市' },
    { value: '商丘', label: '商丘市' },
    { value: '永城', label: '永城市' },
    { value: '信阳', label: '信阳市' },
    { value: '周口', label: '周口市' },
    { value: '项城', label: '项城市' },
    { value: '驻马店', label: '驻马店市' },
    { value: '省直辖县级行政区划', label: '省直辖县级行政区划' },
    { value: '济源', label: '济源市' }
    ]
  },
  {
    value: '湖北省',
    label: '湖北省',
    children: [
    { value: '武汉', label: '武汉市' },
    { value: '黄石', label: '黄石市' },
    { value: '大冶', label: '大冶市' },
    { value: '十堰', label: '十堰市' },
    { value: '丹江口', label: '丹江口市' },
    { value: '宜昌', label: '宜昌市' },
    { value: '宜都', label: '宜都市' },
    { value: '当阳', label: '当阳市' },
    { value: '枝江', label: '枝江市' },
    { value: '襄阳', label: '襄阳市' },
    { value: '老河口', label: '老河口市' },
    { value: '枣阳', label: '枣阳市' },
    { value: '宜城', label: '宜城市' },
    { value: '鄂州', label: '鄂州市' },
    { value: '荆门', label: '荆门市' },
    { value: '钟祥', label: '钟祥市' },
    { value: '京山', label: '京山市' },
    { value: '孝感', label: '孝感市' },
    { value: '应城', label: '应城市' },
    { value: '安陆', label: '安陆市' },
    { value: '汉川', label: '汉川市' },
    { value: '荆州', label: '荆州市' },
    { value: '石首', label: '石首市' },
    { value: '洪湖', label: '洪湖市' },
    { value: '松滋', label: '松滋市' },
    { value: '监利', label: '监利市' },
    { value: '黄冈', label: '黄冈市' },
    { value: '麻城', label: '麻城市' },
    { value: '武穴', label: '武穴市' },
    { value: '咸宁', label: '咸宁市' },
    { value: '赤壁', label: '赤壁市' },
    { value: '随州', label: '随州市' },
    { value: '广水', label: '广水市' },
    { value: '恩施土家族苗族自治州', label: '恩施土家族苗族自治州' },
    { value: '恩施', label: '恩施市' },
    { value: '利川', label: '利川市' },
    { value: '省直辖县级行政区划', label: '省直辖县级行政区划' },
    { value: '仙桃', label: '仙桃市' },
    { value: '潜江', label: '潜江市' },
    { value: '天门', label: '天门市' }
    ]
  },
  {
    value: '湖南省',
    label: '湖南省',
    children: [
    { value: '长沙', label: '长沙市' },
    { value: '浏阳', label: '浏阳市' },
    { value: '宁乡', label: '宁乡市' },
    { value: '株洲', label: '株洲市' },
    { value: '醴陵', label: '醴陵市' },
    { value: '湘潭', label: '湘潭市' },
    { value: '湘乡', label: '湘乡市' },
    { value: '韶山', label: '韶山市' },
    { value: '衡阳', label: '衡阳市' },
    { value: '耒阳', label: '耒阳市' },
    { value: '常宁', label: '常宁市' },
    { value: '邵阳', label: '邵阳市' },
    { value: '武冈', label: '武冈市' },
    { value: '邵东', label: '邵东市' },
    { value: '岳阳', label: '岳阳市' },
    { value: '汨罗', label: '汨罗市' },
    { value: '临湘', label: '临湘市' },
    { value: '常德', label: '常德市' },
    { value: '津市', label: '津市市' },
    { value: '张家界', label: '张家界市' },
    { value: '益阳', label: '益阳市' },
    { value: '沅江', label: '沅江市' },
    { value: '郴州', label: '郴州市' },
    { value: '资兴', label: '资兴市' },
    { value: '永州', label: '永州市' },
    { value: '祁阳', label: '祁阳市' },
    { value: '怀化', label: '怀化市' },
    { value: '洪江', label: '洪江市' },
    { value: '娄底', label: '娄底市' },
    { value: '冷水江', label: '冷水江市' },
    { value: '涟源', label: '涟源市' },
    { value: '湘西土家族苗族自治州', label: '湘西土家族苗族自治州' },
    { value: '吉首', label: '吉首市' }
    ]
  },
  {
    value: '广东省',
    label: '广东省',
    children: [
    { value: '广州', label: '广州市' },
    { value: '韶关', label: '韶关市' },
    { value: '乐昌', label: '乐昌市' },
    { value: '南雄', label: '南雄市' },
    { value: '深圳', label: '深圳市' },
    { value: '珠海', label: '珠海市' },
    { value: '汕头', label: '汕头市' },
    { value: '佛山', label: '佛山市' },
    { value: '江门', label: '江门市' },
    { value: '台山', label: '台山市' },
    { value: '开平', label: '开平市' },
    { value: '鹤山', label: '鹤山市' },
    { value: '恩平', label: '恩平市' },
    { value: '湛江', label: '湛江市' },
    { value: '廉江', label: '廉江市' },
    { value: '雷州', label: '雷州市' },
    { value: '吴川', label: '吴川市' },
    { value: '茂名', label: '茂名市' },
    { value: '高州', label: '高州市' },
    { value: '化州', label: '化州市' },
    { value: '信宜', label: '信宜市' },
    { value: '肇庆', label: '肇庆市' },
    { value: '四会', label: '四会市' },
    { value: '惠州', label: '惠州市' },
    { value: '梅州', label: '梅州市' },
    { value: '兴宁', label: '兴宁市' },
    { value: '汕尾', label: '汕尾市' },
    { value: '陆丰', label: '陆丰市' },
    { value: '河源', label: '河源市' },
    { value: '阳江', label: '阳江市' },
    { value: '阳春', label: '阳春市' },
    { value: '清远', label: '清远市' },
    { value: '英德', label: '英德市' },
    { value: '连州', label: '连州市' },
    { value: '东莞', label: '东莞市' },
    { value: '中山', label: '中山市' },
    { value: '潮州', label: '潮州市' },
    { value: '揭阳', label: '揭阳市' },
    { value: '普宁', label: '普宁市' },
    { value: '云浮', label: '云浮市' },
    { value: '罗定', label: '罗定市' }
    ]
  },
  {
    value: '广西壮族自治区',
    label: '广西壮族自治区',
    children: [
    { value: '南宁', label: '南宁市' },
    { value: '横州', label: '横州市' },
    { value: '柳州', label: '柳州市' },
    { value: '桂林', label: '桂林市' },
    { value: '荔浦', label: '荔浦市' },
    { value: '梧州', label: '梧州市' },
    { value: '岑溪', label: '岑溪市' },
    { value: '北海', label: '北海市' },
    { value: '防城港', label: '防城港市' },
    { value: '东兴', label: '东兴市' },
    { value: '钦州', label: '钦州市' },
    { value: '贵港', label: '贵港市' },
    { value: '桂平', label: '桂平市' },
    { value: '玉林', label: '玉林市' },
    { value: '北流', label: '北流市' },
    { value: '百色', label: '百色市' },
    { value: '靖西', label: '靖西市' },
    { value: '平果', label: '平果市' },
    { value: '贺州', label: '贺州市' },
    { value: '河池', label: '河池市' },
    { value: '来宾', label: '来宾市' },
    { value: '合山', label: '合山市' },
    { value: '崇左', label: '崇左市' },
    { value: '凭祥', label: '凭祥市' }
    ]
  },
  {
    value: '海南省',
    label: '海南省',
    children: [
    { value: '海口', label: '海口市' },
    { value: '三亚', label: '三亚市' },
    { value: '三沙', label: '三沙市' },
    { value: '儋州', label: '儋州市' },
    { value: '省直辖县级行政区划', label: '省直辖县级行政区划' },
    { value: '五指山', label: '五指山市' },
    { value: '琼海', label: '琼海市' },
    { value: '文昌', label: '文昌市' },
    { value: '万宁', label: '万宁市' },
    { value: '东方', label: '东方市' }
    ]
  },
  { value: '重庆', label: '重庆市' },
  {
    value: '四川省',
    label: '四川省',
    children: [
    { value: '成都', label: '成都市' },
    { value: '都江堰', label: '都江堰市' },
    { value: '彭州', label: '彭州市' },
    { value: '邛崃', label: '邛崃市' },
    { value: '崇州', label: '崇州市' },
    { value: '简阳', label: '简阳市' },
    { value: '自贡', label: '自贡市' },
    { value: '攀枝花', label: '攀枝花市' },
    { value: '泸州', label: '泸州市' },
    { value: '德阳', label: '德阳市' },
    { value: '广汉', label: '广汉市' },
    { value: '什邡', label: '什邡市' },
    { value: '绵竹', label: '绵竹市' },
    { value: '绵阳', label: '绵阳市' },
    { value: '江油', label: '江油市' },
    { value: '广元', label: '广元市' },
    { value: '遂宁', label: '遂宁市' },
    { value: '射洪', label: '射洪市' },
    { value: '内江', label: '内江市' },
    { value: '隆昌', label: '隆昌市' },
    { value: '乐山', label: '乐山市' },
    { value: '峨眉山', label: '峨眉山市' },
    { value: '南充', label: '南充市' },
    { value: '阆中', label: '阆中市' },
    { value: '眉山', label: '眉山市' },
    { value: '宜宾', label: '宜宾市' },
    { value: '广安', label: '广安市' },
    { value: '华蓥', label: '华蓥市' },
    { value: '达州', label: '达州市' },
    { value: '万源', label: '万源市' },
    { value: '雅安', label: '雅安市' },
    { value: '巴中', label: '巴中市' },
    { value: '资阳', label: '资阳市' },
    { value: '阿坝藏族羌族自治州', label: '阿坝藏族羌族自治州' },
    { value: '马尔康', label: '马尔康市' },
    { value: '甘孜藏族自治州', label: '甘孜藏族自治州' },
    { value: '康定', label: '康定市' },
    { value: '凉山彝族自治州', label: '凉山彝族自治州' },
    { value: '西昌', label: '西昌市' },
    { value: '会理', label: '会理市' }
    ]
  },
  {
    value: '贵州省',
    label: '贵州省',
    children: [
    { value: '贵阳', label: '贵阳市' },
    { value: '清镇', label: '清镇市' },
    { value: '六盘水', label: '六盘水市' },
    { value: '盘州', label: '盘州市' },
    { value: '遵义', label: '遵义市' },
    { value: '赤水', label: '赤水市' },
    { value: '仁怀', label: '仁怀市' },
    { value: '安顺', label: '安顺市' },
    { value: '毕节', label: '毕节市' },
    { value: '黔西', label: '黔西市' },
    { value: '铜仁', label: '铜仁市' },
    { value: '黔西南布依族苗族自治州', label: '黔西南布依族苗族自治州' },
    { value: '兴义', label: '兴义市' },
    { value: '兴仁', label: '兴仁市' },
    { value: '黔东南苗族侗族自治州', label: '黔东南苗族侗族自治州' },
    { value: '凯里', label: '凯里市' },
    { value: '黔南布依族苗族自治州', label: '黔南布依族苗族自治州' },
    { value: '都匀', label: '都匀市' },
    { value: '福泉', label: '福泉市' }
    ]
  },
  {
    value: '云南省',
    label: '云南省',
    children: [
    { value: '昆明', label: '昆明市' },
    { value: '安宁', label: '安宁市' },
    { value: '曲靖', label: '曲靖市' },
    { value: '宣威', label: '宣威市' },
    { value: '玉溪', label: '玉溪市' },
    { value: '澄江', label: '澄江市' },
    { value: '保山', label: '保山市' },
    { value: '腾冲', label: '腾冲市' },
    { value: '昭通', label: '昭通市' },
    { value: '水富', label: '水富市' },
    { value: '丽江', label: '丽江市' },
    { value: '普洱', label: '普洱市' },
    { value: '临沧', label: '临沧市' },
    { value: '楚雄彝族自治州', label: '楚雄彝族自治州' },
    { value: '楚雄', label: '楚雄市' },
    { value: '禄丰', label: '禄丰市' },
    { value: '红河哈尼族彝族自治州', label: '红河哈尼族彝族自治州' },
    { value: '个旧', label: '个旧市' },
    { value: '开远', label: '开远市' },
    { value: '蒙自', label: '蒙自市' },
    { value: '弥勒', label: '弥勒市' },
    { value: '文山壮族苗族自治州', label: '文山壮族苗族自治州' },
    { value: '文山', label: '文山市' },
    { value: '西双版纳傣族自治州', label: '西双版纳傣族自治州' },
    { value: '景洪', label: '景洪市' },
    { value: '大理白族自治州', label: '大理白族自治州' },
    { value: '大理', label: '大理市' },
    { value: '德宏傣族景颇族自治州', label: '德宏傣族景颇族自治州' },
    { value: '瑞丽', label: '瑞丽市' },
    { value: '芒', label: '芒市' },
    { value: '怒江傈僳族自治州', label: '怒江傈僳族自治州' },
    { value: '泸水', label: '泸水市' },
    { value: '迪庆藏族自治州', label: '迪庆藏族自治州' },
    { value: '香格里拉', label: '香格里拉市' }
    ]
  },
  {
    value: '西藏自治区',
    label: '西藏自治区',
    children: [
    { value: '拉萨', label: '拉萨市' },
    { value: '日喀则', label: '日喀则市' },
    { value: '昌都', label: '昌都市' },
    { value: '林芝', label: '林芝市' },
    { value: '米林', label: '米林市' },
    { value: '山南', label: '山南市' },
    { value: '错那', label: '错那市' },
    { value: '那曲', label: '那曲市' },
    { value: '阿里地区', label: '阿里地区' }
    ]
  },
  {
    value: '陕西省',
    label: '陕西省',
    children: [
    { value: '西安', label: '西安市' },
    { value: '铜川', label: '铜川市' },
    { value: '宝鸡', label: '宝鸡市' },
    { value: '咸阳', label: '咸阳市' },
    { value: '兴平', label: '兴平市' },
    { value: '彬州', label: '彬州市' },
    { value: '渭南', label: '渭南市' },
    { value: '韩城', label: '韩城市' },
    { value: '华阴', label: '华阴市' },
    { value: '延安', label: '延安市' },
    { value: '子长', label: '子长市' },
    { value: '汉中', label: '汉中市' },
    { value: '榆林', label: '榆林市' },
    { value: '神木', label: '神木市' },
    { value: '安康', label: '安康市' },
    { value: '旬阳', label: '旬阳市' },
    { value: '商洛', label: '商洛市' }
    ]
  },
  {
    value: '甘肃省',
    label: '甘肃省',
    children: [
    { value: '兰州', label: '兰州市' },
    { value: '嘉峪关', label: '嘉峪关市' },
    { value: '金昌', label: '金昌市' },
    { value: '白银', label: '白银市' },
    { value: '天水', label: '天水市' },
    { value: '武威', label: '武威市' },
    { value: '张掖', label: '张掖市' },
    { value: '平凉', label: '平凉市' },
    { value: '华亭', label: '华亭市' },
    { value: '酒泉', label: '酒泉市' },
    { value: '玉门', label: '玉门市' },
    { value: '敦煌', label: '敦煌市' },
    { value: '庆阳', label: '庆阳市' },
    { value: '定西', label: '定西市' },
    { value: '陇南', label: '陇南市' },
    { value: '临夏回族自治州', label: '临夏回族自治州' },
    { value: '临夏', label: '临夏市' },
    { value: '甘南藏族自治州', label: '甘南藏族自治州' },
    { value: '合作', label: '合作市' }
    ]
  },
  {
    value: '青海省',
    label: '青海省',
    children: [
    { value: '西宁', label: '西宁市' },
    { value: '海东', label: '海东市' },
    { value: '海北藏族自治州', label: '海北藏族自治州' },
    { value: '黄南藏族自治州', label: '黄南藏族自治州' },
    { value: '同仁', label: '同仁市' },
    { value: '海南藏族自治州', label: '海南藏族自治州' },
    { value: '果洛藏族自治州', label: '果洛藏族自治州' },
    { value: '玉树藏族自治州', label: '玉树藏族自治州' },
    { value: '玉树', label: '玉树市' },
    { value: '海西蒙古族藏族自治州', label: '海西蒙古族藏族自治州' },
    { value: '格尔木', label: '格尔木市' },
    { value: '德令哈', label: '德令哈市' },
    { value: '茫崖', label: '茫崖市' }
    ]
  },
  {
    value: '宁夏回族自治区',
    label: '宁夏回族自治区',
    children: [
    { value: '银川', label: '银川市' },
    { value: '灵武', label: '灵武市' },
    { value: '石嘴山', label: '石嘴山市' },
    { value: '吴忠', label: '吴忠市' },
    { value: '青铜峡', label: '青铜峡市' },
    { value: '固原', label: '固原市' },
    { value: '中卫', label: '中卫市' }
    ]
  },
  {
    value: '新疆维吾尔自治区',
    label: '新疆维吾尔自治区',
    children: [
    { value: '乌鲁木齐', label: '乌鲁木齐市' },
    { value: '克拉玛依', label: '克拉玛依市' },
    { value: '吐鲁番', label: '吐鲁番市' },
    { value: '哈密', label: '哈密市' },
    { value: '昌吉回族自治州', label: '昌吉回族自治州' },
    { value: '昌吉', label: '昌吉市' },
    { value: '阜康', label: '阜康市' },
    { value: '博尔塔拉蒙古自治州', label: '博尔塔拉蒙古自治州' },
    { value: '博乐', label: '博乐市' },
    { value: '阿拉山口', label: '阿拉山口市' },
    { value: '巴音郭楞蒙古自治州', label: '巴音郭楞蒙古自治州' },
    { value: '库尔勒', label: '库尔勒市' },
    { value: '阿克苏地区', label: '阿克苏地区' },
    { value: '阿克苏', label: '阿克苏市' },
    { value: '库车', label: '库车市' },
    { value: '克孜勒苏柯尔克孜自治州', label: '克孜勒苏柯尔克孜自治州' },
    { value: '阿图什', label: '阿图什市' },
    { value: '喀什地区', label: '喀什地区' },
    { value: '喀什', label: '喀什市' },
    { value: '和田地区', label: '和田地区' },
    { value: '和田', label: '和田市' },
    { value: '伊犁哈萨克自治州', label: '伊犁哈萨克自治州' },
    { value: '伊宁', label: '伊宁市' },
    { value: '奎屯', label: '奎屯市' },
    { value: '霍尔果斯', label: '霍尔果斯市' },
    { value: '塔城地区', label: '塔城地区' },
    { value: '塔城', label: '塔城市' },
    { value: '乌苏', label: '乌苏市' },
    { value: '沙湾', label: '沙湾市' },
    { value: '阿勒泰地区', label: '阿勒泰地区' },
    { value: '阿勒泰', label: '阿勒泰市' },
    { value: '自治区直辖县级行政区划', label: '自治区直辖县级行政区划' },
    { value: '石河子', label: '石河子市' },
    { value: '阿拉尔', label: '阿拉尔市' },
    { value: '图木舒克', label: '图木舒克市' },
    { value: '五家渠', label: '五家渠市' },
    { value: '北屯', label: '北屯市' },
    { value: '铁门关', label: '铁门关市' },
    { value: '双河', label: '双河市' },
    { value: '可克达拉', label: '可克达拉市' },
    { value: '昆玉', label: '昆玉市' },
    { value: '胡杨河', label: '胡杨河市' },
    { value: '新星', label: '新星市' },
    { value: '白杨', label: '白杨市' }
    ]
  },
  { value: '香港', label: '香港特别行政区' },
  { value: '澳门', label: '澳门特别行政区' },
  {
    value: '台湾省',
    label: '台湾省',
    children: [
    { value: '台北', label: '台北市' },
    { value: '新北', label: '新北市' },
    { value: '桃园', label: '桃园市' },
    { value: '新竹', label: '新竹市' },
    { value: '台中', label: '台中市' },
    { value: '台南', label: '台南市' },
    { value: '高雄', label: '高雄市' }
    ]
  }
]
